init_config:

instances:
  - prometheus_url: http://127.0.0.1:8080/metrics
    namespace: "pulsar"
    metrics:
      - _*
    health_service_check: true
    prometheus_timeout: 1000
    max_returned_metrics: 1000000
    type_overrides:
      pulsar_topics_count: gauge
      pulsar_rate_in: gauge
      pulsar_rate_out: gauge
      pulsar_subscriptions_count: gauge
      pulsar_producers_count: gauge
      pulsar_consumers_count: gauge
      pulsar_throughput_in: gauge
      pulsar_throughput_out: gauge
      pulsar_storage_size: gauge
      pulsar_msg_backlog: gauge
      pulsar_storage_backlog_size: gauge
      pulsar_storage_offloaded_size: gauge
      pulsar_storage_write_latency_le_0_5: gauge
      pulsar_storage_write_latency_le_1: gauge
      pulsar_storage_write_latency_le_5: gauge
      pulsar_storage_write_latency_le_10: gauge
      pulsar_storage_write_latency_le_20: gauge
      pulsar_storage_write_latency_le_50: gauge
      pulsar_storage_write_latency_le_100: gauge
      pulsar_storage_write_latency_le_200: gauge
      pulsar_storage_write_latency_le_1000: gauge
      pulsar_storage_write_latency_overflow: gauge
      pulsar_entry_size_le_128: gauge
      pulsar_entry_size_le_512: gauge
      pulsar_entry_size_le_1_kb: gauge
      pulsar_entry_size_le_2_kb: gauge
      pulsar_entry_size_le_4_kb: gauge
      pulsar_entry_size_le_16_kb: gauge
      pulsar_entry_size_le_100_kb: gauge
      pulsar_entry_size_le_1_mb: gauge
      pulsar_entry_size_le_overflow: gauge
      pulsar_subscription_back_log: gauge
      pulsar_subscription_back_log_no_delayed: gauge
      pulsar_subscription_delayed: gauge
      pulsar_subscription_msg_rate_redeliver: gauge
      pulsar_subscription_unacked_messages: gauge
      pulsar_subscription_blocked_on_unacked_messages: gauge
      pulsar_subscription_msg_rate_out: gauge
      pulsar_subscription_msg_throughput_out: gauge
      pulsar_in_bytes_total: counter
      pulsar_in_messages_total: counter
      topic_load_times: counter
      jvm_memory_bytes_used: gauge
      jvm_memory_bytes_committed: gauge
      jvm_memory_bytes_max: gauge
      jvm_memory_bytes_init: gauge
      jvm_memory_pool_bytes_used: gauge
      jvm_memory_pool_bytes_committed: gauge
      jvm_memory_pool_bytes_max: gauge
      jvm_memory_pool_bytes_init: gauge
      jvm_classes_loaded: gauge
      jvm_classes_loaded_total: counter
      jvm_classes_unloaded_total: counter
      jvm_buffer_pool_used_bytes: gauge
      jvm_buffer_pool_capacity_bytes: gauge
      jvm_buffer_pool_used_buffers: gauge
      jvm_threads_current: gauge
      jvm_threads_daemon: gauge
      jvm_threads_peak: gauge
      jvm_threads_started_total: counter
      jvm_threads_deadlocked: gauge
      jvm_threads_deadlocked_monitor: gauge
      jvm_gc_collection_seconds_count: gauge
      jvm_gc_collection_seconds_sum: gauge
      jvm_memory_direct_bytes_max: gauge
    tags:
      - pulsar-broker:<your-broker-id>